[package]
name = "photobooth"
version = "0.1.0"
authors = ["Frulko <guillaume.dumoulin@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.13.0"
gphoto = "0.1.2"
serde_json = "1.0"
